<?php

declare(strict_types=1);

namespace Drupal\vs_voting\Normalizer;

/**
 * Normalizes aggregated voting results.
 */
final class VotingResultsNormalizer {

  /**
   * Normalizes results data.
   *
   * @param array<string, mixed> $results
   *   The results payload generated by the results' manager.
   *
   * @return array<string, mixed>
   *   The API payload.
   */
  public function normalize(array $results): array {
    return $results;
  }

}
